MySorbet/sorbet-app

src/app/page.tsx
Description & Technical Solution
- Removes edit mode for editing widgets on mobile devices. Creates 'isMobile' boolean state where WidgetContainer is rendered and passes it down to WidgetContainer.
- 'Mobile' sizing is set at 768px, which includes tablets. Not sure if we are accounting for tablets, but included them to be safe.
- Handles edit flow for mobile devices, forcing users to edit on desktop for better UX.
- Potential for rendering bugs when editing in mobile due to react-grid-layout, our defined breakpoints, and not having enough space on mobile.
- This PR simply …
=> Disables edit mode for mobile screens

src/app/gigs/chat/chat-layout-minimal.tsx
- Refreshes channel every time a user sends a message so that we can see if the other user is `online` or `offline`.
- There was an issue where the `connectionStatus` would be stale and not properly update. Then a user would receive a message notification even though the chat is open.
[ x ] Rebase with main
=> Hotfix for connectionStatus bug

src/components/profile/profile-header.tsx
- Implements allowing users to copy their link to their clipboard when clicking the 'Share' button on their profile.
- Uses window origin to grab the base url and then uses `Clipboard API` to copy to clipboard.
=> Hotfix for sharing profiles

src/components/profile/profile-edit-modal.tsx, src/components/profile/profile-header.tsx, src/components/profile/widgets/add-widgets.tsx, src/components/profile/widgets/widget-container.tsx, src/components/profile/widgets/widget-link.tsx
- Fixes image overflow issue by adding `overflow-hidden` style to  div wrapping `BannerImage` component for 4x2 widget in `widget-link.tsx` file.
- Also fixes ESLint warnings in `widget-link.tsx`,`widget-container.tsx`, and `add-widgets.tsx`
=> Fixes image overflow for image on 4x2 widget (SRBT-132)

src/components/profile/widgets/widget-container.tsx, src/components/profile/widgets/widget-instagram.tsx, src/components/profile/widgets/widget-link.tsx, src/hooks/widgets/useGetWidgetContent.ts, src/lib/service/widgets.ts, src/types/widgets.ts
- Implements UI for private instagram accounts and instagram accounts that are valid, but haven't posted any pictures.
- Updates `handleWidgetAdd` function in `widget-container` by removing the try catch and allowing React Query to handle the error situation with the `onError` callback function.
- Before, it was the same toast for each and every widget failure. Now, in `useGetWidgetContent.ts`, the error message that it receives is the error message that is toasted. We just need to make sure that each function that is called in `useGetWidgetContent` is throwing a descriptive message.
- Also fixes the 4x2 media being too small (simple fix from `max-h-full` to `h-full`)
https://github.com/user-attachments/assets/bb2853b1-eaa3-4882-99c6-d13c80bd166a
=> Updates instagram widget SRBT-140

package.json, src/components/profile/profile-edit-modal.tsx, src/components/profile/share/share-profile-dialog.tsx, src/components/profile/share/views/share-your-profile.tsx, src/components/ui/dialog.tsx, yarn.lock
- Adds `react-use-measure` package that calculates height of a component
- Implements framer motion to animate height changes
- Changes `customDialogClose: string` prop to `hideDefaultCloseButton: boolean` in shadcn `dialog` component for better readability.
** Opted not to add the horizontal animations because I felt that it would be too much and very distracting. Felt that opacity and height resize animation is clean and sleek. Open to discussion tho!
If it were something like this: https://ui.lukacho.com/components/dropdown-menu where a user has a sense of direction because everything is displayed, then i think a horizontal slide makes sense. I digress, but these are just my thoughts.
https://github.com/user-attachments/assets/3d3b3ebc-c809-4345-9753-ae5910eb8a60
=> Adds animation on resize for share profile dialog

src/components/onboarding/signup/step1.tsx, src/components/profile/location-input.tsx, src/components/profile/profile-edit-modal.tsx, src/components/syntax-ui/skill-input.tsx
- Disables `save` button when a user has not made any changes
- For `location-input` and `skill-input` and profile image, this is done through the `setValue` function by passing `shouldDirty` as the options argument.
- Adds `isImageUpdated` property to zod schema so that we can easily check if the image field is dirty through React Hook Form. (The image is not controlled by RHF, but rather local state instead.)
- Implements an effect to reset the form and update default values only when the form has been successfully submitted.
- Form wasn't syncing to latest changes on save
** Also fixes step1, only disabling continue button on first render (no dirty fields), and when required fields are filled out (`isValid`)
https://github.com/user-attachments/assets/10af48da-5ba3-495c-ac53-18729c3407b2 …
=> SRBT-148 Adds proper disabled state for save button in profile edit modal

src/components/notifications/notification-toasts.tsx, src/components/notifications/notifications.tsx, src/components/ui/toast.tsx, src/components/ui/toaster.tsx
**Changes**
- Implements redirect functionality for Knock feed and toast when items are clicked
- Adds `href` property to `ToastProps` in `toast.tsx`
- Adds `a` tag wrapping the toast content in `toaster.tsx`
- Adds `onNotificationClick` callback to trigger a redirect to `/gigs` for now
- Note:
- State still needs to be raised to url for select routes, just waiting on the development of that as there may be changes to gigs.
=> Update notifications with redirect functionality

src/app/layout.tsx, src/components/profile/widgets/widget-grid.tsx, src/styles/globals.css
By hiding horizontal scroll on `html` and adding a `fix-modal-layout-shift` utility for special cases
=> Fix layout shift

src/components/ui/toast.tsx
**Changes**
- Adds jsdoc comment properly for `href` in `toast.tsx`
=> Minor housekeeping

src/components/profile/widgets/invalid-alert.tsx
**Changes**
- Clicking on the "Learn More" button when an invalid alert appear redirects users to the documentation.
=> [SRBT-263] fix(invalid-alert): added an external link to sorbet documentation

package.json, yarn.lock
**Changes**
- Update storybook and plugins  to `8.4.1` (fixes warnings when running `yarn sb`)
- Add missing peer deps (`prop-types` and `webpack` -- fixes warnings when running `yarn`)
=> Storybook update and peer dep fixes

src/app/wallet/all/transactions-table.tsx, src/app/wallet/funds-flow.tsx, src/app/wallet/utils.tsx, src/app/wallet/wallet-balance.tsx, src/app/wallet/wallet-container.tsx
**Changes**
- Wallet container width has been adjusted to be a maximum of 1080px as per the Figma.
- Wallet Address are now truncated to only show the first three digits and last four digits.
*Using mock data*
=> [SRBT-330] Adjusted wallet container width + added wallet truncation

src/app/wallet/wallet-send-dialog.tsx
- Removes spell check for eth address input
- Adds `DialogDescription` to `Step2` of the dialog
=> Minor upgrades to wallet send dialog

src/app/wallet/all/transactions-table.tsx, src/app/wallet/funds-flow.tsx, src/app/wallet/my-accounts.tsx, src/app/wallet/wallet-balance.tsx, src/app/wallet/wallet-container.tsx, src/hooks/web3/use-wallet-balances.ts
[SRBT-343] Wallet Page Skeletons for Loading + Shadow Fixes
Also a correction for [SRBT-344](https://linear.app/mysorbet/issue/SRBT-344/consistent-shadows-on-wallet-page-cards) and [SRBT-336](https://linear.app/mysorbet/issue/SRBT-336/wallet-balance-update-delay-may-cause-user-confusion) 
**Changes**
- When the page is loading, skeleton components are rendered instead of the actual cards themselves to reduce confusion about what the actual wallet balance is, etc. In the case of the Wallet Balance Card, there's a skeleton component for just the balance actual value changing (regarding SRBT-336), since the balance loading != page loading necessarily (like in the case of adding funds)
- All cards now have the same box-shadow value (`shadow-md`), instead of arbitrary values …
=> [SRBT-343] Wallet Page Skeletons for Loading + Shadow Fixes

src/components/profile/widgets/add-widgets.tsx
**Changes**
- Refactored the SectionTitleIcon to be wrapped in a `div` instead of an `svg`.  I also refactored the Tooltip Trigger for section titles to be a button. Apparently, Tooltips can only to appear on [buttons](https://github.com/radix-ui/primitives/issues/955#issuecomment-960610209), or elements that require a click / pointer-down interaction – from what I've gathered on the documentation beyond this specific GitHub issue.
=> Fix: Tooltip Not Appearing for "Add Section Title"

src/components/profile/widgets/add-widgets.tsx, src/components/profile/widgets/modify-image-controls.tsx, src/components/profile/widgets/util.tsx, src/components/profile/widgets/widget-link.tsx, src/components/profile/widgets/widget-linkedin-profile.tsx, src/hooks/profile/useLayoutManagement.ts, src/hooks/profile/useWidgetManagement.ts
Also addresses SRBT 359
**Changes**
- You shouldn't need to refresh the page to see the widget images get replaced and/or restored
- LinkedIn Widget stylings got refactored so you can visually see the changes working
- Restore Image Icon was sized up
Screenshots/videos of the changes made (if any, otherwise delete this section)
https://github.com/user-attachments/assets/08a827a6-aff1-4677-80cd-623dea833e4a
=> [SRBT-358] Widget replace and restore images

src/components/profile/widgets/widget-medium.tsx
**Changes**
- In layout C, there was an extra medium icon. It is now removed.
- In layout D, the modify widget bar above the image was clipped. It's now fully visible.
=> [SRBT-372] Fix Layout C and D for Medium Widgets

src/components/profile/widgets/widget-section.tsx, src/components/profile/widgets/widget.tsx
**Changes**
- I've added additional prop (`editMode`) to section titles widgets, similar to what the other widget types have, to disable a user from editing the text of a section widget if they're aren't authorized to do so.
https://github.com/user-attachments/assets/aa27647c-29fc-453d-887e-72c632600d41
=> [SRBT-371] User can only edit section titles when signed in

src/components/profile/widgets/resize-widget.tsx, src/components/profile/widgets/widget-grid.tsx, src/components/profile/widgets/widget-section.tsx, src/components/profile/widgets/widget.tsx, src/hooks/profile/useLayoutManagement.ts, src/hooks/profile/useWidgetManagement.ts
Due to the changes explained below, this PR also addresses [SRBT-345](https://linear.app/mysorbet/issue/SRBT-345/look-into-dual-toast-error-for-section-titles).
**Changes**
* Refactored the loading states of the profile page to instead only put a widget that's being directly modified (i.e. new image upload, restoring image, etc.) into a loading state.
* Notably, I refactored several of the `onClick` functions in `widget.tsx` to resolve some of the deeper issues with race conditions happening on the profile page, like so:
* old way: `onClick={(e) => {
handleRemove(identifier);
}}`
* new way: `onMouseDown={(e) => {
e.stopPropagation();
handleRemove(identifier);
}}`
* When `onClick` is used, it's technically consider a "dragging" motion by …
=>  [SRBT-375] Add loading state if widget is being modified

src/api/widgets.ts, src/components/profile/widgets/banner-image.tsx, src/components/profile/widgets/modify-image-controls.tsx, src/components/profile/widgets/widget-behance.tsx, src/components/profile/widgets/widget-dribbble.tsx, src/components/profile/widgets/widget-github.tsx, src/components/profile/widgets/widget-instagram.tsx, src/components/profile/widgets/widget-link.tsx, src/components/profile/widgets/widget-linkedin-profile.tsx, src/components/profile/widgets/widget-medium.tsx, src/components/profile/widgets/widget-soundcloud.tsx, src/components/profile/widgets/widget-substack.tsx, src/components/profile/widgets/widget-twitter.tsx, src/components/profile/widgets/widget-youtube.tsx, src/components/profile/widgets/widget.tsx, src/hooks/profile/useWidgetManagement.ts, src/hooks/widgets/useRestoreInstagramWidget.ts, src/types/widgets.ts
**Changes**
- Users can use the instagram profile's most recent posts, or they have the option of using a cover image. The precedent of which gets displaying is instagram posts (if they exist) -> cover image -> whatever appropriate placeholder text for when there's neither.
- Simplified `restoreWidgetImageAsync` to not need a content parameter to reduce payload size. Wasn't even needed for the corresponding backend function to work anyways.
- For handling image restorations for instagram widgets, a new endpoint was made and that gets called by `restoreInstagramWidgetAsync` instead of `restoreWidgetImageAsync`. For context, each individual instagram image is ~500 kb, which means the flow of fetching an image and then updating the widget with said image doesn't work because because that …
=> [SRBT-355] Instagram widget image replacement and restoring

.storybook/preview.ts, package.json, src/api/images.ts, src/api/transactions/msw-handlers.ts, src/api/widgets-v2.ts, src/api/widgets-v2/images.ts, src/api/widgets-v2/index.ts, src/api/widgets-v2/msw-handlers.ts, src/api/widgets-v2/types.ts, src/api/widgets-v2/widgets-v2.ts, src/app/v2/[handle]/components/profile.stories.tsx, src/app/v2/[handle]/components/profile.tsx, src/app/v2/[handle]/components/widget/grid-config.ts, src/app/v2/[handle]/components/widget/grid-error-fallback.tsx, src/app/v2/[handle]/components/widget/grid.stories.tsx, src/app/v2/[handle]/components/widget/grid.tsx, src/app/v2/[handle]/components/widget/image-widget.tsx, src/app/v2/[handle]/components/widget/use-abort-map.ts, src/app/v2/[handle]/components/widget/use-handle-paste.ts, src/app/v2/[handle]/components/widget/use-pending-widgets.ts, src/app/v2/[handle]/components/widget/use-widget-context.tsx, src/app/v2/[handle]/components/widget/widget.tsx, src/app/v2/[handle]/page.tsx
**Changes**
- Use a reducer for widget state and actions
- Add grid fallback
- Grid handles paste events
- Fail silently on layout mismatch to improve UX
- Add widget API v2 layer with image support
- Connect grid reducer to RQ network calls
- Enrich widgets when adding
- Silence msw logs
- Do not auto open sb and change port to 6300
=> Connect widget grid to network

src/app/splash.tsx, src/app/v2/[handle]/components/profile.tsx, src/app/v2/[handle]/components/widget/widget.stories.tsx, src/app/v2/[handle]/components/widget/widget.tsx
**Changes**
- Render back to dashboard on your own profile
- Use og aspect on A size and fix D size crush
- opt all favicons in to a litttle bit of rounding 
- Widgets are select-none
- Fix splash page not being full size
Storybook
- fix string interpolation on widget stories
- automatic size containers for widget stories
- add long title story to widget
- widget stories use sorbet content
=> Widgets V2 Fixes

src/api/widgets-v2/mock-widgets.ts, src/api/widgets-v2/msw-handlers.ts, src/api/widgets-v2/types.ts, src/app/[handle]/components/profile.stories.tsx, src/app/[handle]/components/profile.tsx, src/app/[handle]/components/widget/grid-config.ts, src/app/[handle]/components/widget/grid.tsx, src/app/[handle]/components/widget/social-icon.tsx, src/app/[handle]/components/widget/use-widget-context.tsx, src/app/[handle]/components/widget/widget.stories.tsx, src/app/[handle]/components/widget/widget.tsx, src/app/[handle]/page.stories.tsx, src/components/common/inline-edit/inline-edit.stories.tsx, src/components/common/inline-edit/inline-edit.tsx
**Changes**
- Make titles in widgets editable
- Add an inline editable component and render in widget
- The widget grid kicks off network updates from this callback
- Update MSW handlers to be more realistic
- Update ApiWidget to use nulls instead of undefined. And then shim conversion to UI types
- Fix some minor styles for D widgets
- add more mocking to stories
- fade in left side of profile
=> Title Editing

.vscode/typescriptreact.code-snippets, src/app/[handle]/components/artificial-mobile.stories.tsx, src/app/[handle]/components/artificial-mobile.tsx, src/app/[handle]/components/control-bar/control-bar.stories.tsx, src/app/[handle]/components/control-bar/control-bar.tsx, src/app/[handle]/components/mobile-switch/animated-tabs.stories.tsx, src/app/[handle]/components/mobile-switch/animated-tabs.tsx, src/app/[handle]/components/mobile-switch/mobile-switch.stories.tsx, src/app/[handle]/components/mobile-switch/mobile-switch.tsx, src/app/[handle]/components/mobile-switch/new-feature-badge.tsx, src/app/[handle]/components/profile.tsx, src/app/[handle]/components/widget/grid.tsx, src/hooks/use-container-query.stories.tsx, src/hooks/use-container-query.tsx
**Main Changes**
- Add `animated-tabs` component based on build-ui and tweaked for our use case
- Add `mobile-switch` which specialized the above with icons and state
- Add mobile switch to control bar and pass props up
- Render a temporary 'new' badge on the mobile switch
- Add a `artificial-mobile` component to wrap the profile and constrain it to an artificial mobile viewport when told to do so by the `mobile-switch`
- Bring all of the above together with state in `profile`
- Profile breaks to mobile layout at 81rem to get rid of confusing half mobile half desktop layout
- Share profile -> share and make the button shine
**Additional Changes**
- Add a storybook code snippet for faster story creation
- Add a `use-container-query` hook to bring container queries into state
- Update the …
=> [SRBT-433] Implement Mobile Switch

src/api/widgets-v2/mock-widgets.ts, src/api/widgets-v2/msw-handlers.ts, src/api/widgets-v2/sample-layout.ts, src/api/widgets-v2/types.ts, src/api/widgets-v2/widgets-v2.ts, src/app/[handle]/components/profile.stories.tsx, src/app/[handle]/components/widget/grid-config.ts, src/app/[handle]/components/widget/grid-reducer.tsx, src/app/[handle]/components/widget/grid.stories.tsx, src/app/[handle]/components/widget/use-widget-context.tsx, src/app/[handle]/components/widget/widget.stories.tsx, src/app/[handle]/components/widget/widget.tsx
**Changes**
- Grid reducer will store nulls rather than undefined 
- move widget reducer to its own file
- use more appropriate names for reducer actions
- Add two E sized widgets to samples
- Consolidate and relocate WidgetData and UpdateDto
- Make grid story functional
- Clean up widget story
=> Organize and Refactor Grid

src/api/widgets-v2/mock-widgets.ts, src/api/widgets-v2/msw-handlers.ts, src/api/widgets-v2/sample-layout.ts, src/api/widgets-v2/types.ts, src/app/[handle]/components/control-bar/add-image-button.tsx, src/app/[handle]/components/control-bar/invisible-input.tsx, src/app/[handle]/components/profile.stories.tsx, src/app/[handle]/components/widget/grid-reducer.tsx, src/app/[handle]/components/widget/grid.tsx, src/app/[handle]/components/widget/use-widget-context.tsx, src/app/[handle]/components/widget/widget-controls/control-button.tsx, src/app/[handle]/components/widget/widget-controls/preview-controls.stories.tsx, src/app/[handle]/components/widget/widget-controls/preview-controls.tsx, src/app/[handle]/components/widget/widget.tsx, src/components/ui/tooltip.tsx
**Changes**
- Abstract out and share InvisibleInput
- Add and render `PreviewControls` in `Widget`
- Add `userContentUrl` and `hideContent` to widget data
- `mockUpdateWidgetHandler` updates all widget data
- `ControlButton`s prevent default to avoid clicking widgets underneath
- Refactoring and renaming in `grid` to increase clarity
- Use `ease-out` curves for controls
- Add `updatePreview` to `WidgetContext` to allow the updating of a preview image with automatic image upload
- `updateWidgetMutation` will abort in progress image uploads if userContentUrl goes to null
- `Widget` will prefer `userContentUrl` over `contentUrl` similar to `usertTitle`. `hideContent` will override both.
- add `MineDisableMSW` story
- Add missing Portal to `tooltip`
=> [SRBT-432] Implement Preview Controls
