MySorbet/sorbet-app

- src/api/user.ts
- src/app/wallet/data-table.tsx
- src/app/wallet/wallet-container.tsx
- src/components/Header/header.tsx
- src/components/profile/widget.tsx
- src/components/sidebar/sidebar.tsx
- src/hooks/useAuth.tsx
- src/types/user.ts
> feat(transactions): integrate transactions backend

- .env.example
- src/api/user.ts
- src/components/profile/add-widgets.tsx
- src/components/profile/invalid-alert.tsx
- src/components/profile/profile-edit-modal.tsx
- src/components/profile/profile-header.tsx
- src/components/profile/widget-container.tsx
- src/components/sidebar/sidebar.tsx
- src/hooks/useAuth.tsx
- src/lib/config.ts
- src/lib/service/widgets.ts
> feat(profile): improve user profile experience

- src/components/profile/add-widgets.tsx
- src/components/profile/profile-header.tsx
- src/components/profile/resize-widget.tsx
- src/components/profile/widget-container.tsx
- src/components/profile/widget-photo.tsx
- src/types/widgets.ts
> feat(widgets): make widgets responsive

- src/api/user.ts
- src/app/[username]/page.tsx
- src/app/container.tsx
- src/app/layout.tsx
- src/app/page.tsx
- src/app/signin/page.tsx
- src/app/signup/page.tsx
- src/app/wallet/page.tsx
- src/components/common/loading/Loading.tsx
- src/components/common/near-wallet/walletSelectorContext.tsx
- src/components/profile/index.ts
- src/components/profile/input-location.tsx
- src/components/profile/input-skills.tsx
- src/components/profile/no-widgets-content.tsx
- src/components/profile/profile-edit-modal.tsx
- src/components/profile/profile-header.tsx
- src/components/profile/profile.tsx
- src/components/profile/widget-container.tsx
- src/components/sidebar/sidebar.tsx
- src/components/ui/toast.tsx
- src/hooks/useAuth.tsx
- src/lib/service/widgets.ts
- src/utils/index.ts
> feat: login with simple email

- package.json
- Updates script syntax to be consistent with `sorbet-api` repo (as per request).
- A little annoying to have different script names for development and prod across both repos.
- Adds consistency to scripts for improved DX.
- Consistent script commands as requested by Humza.
- "dev" --> "start:dev"
- "start" --> "start:prod"
- Now consistent with `sorbet-api` repo
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] Already rebased against main branch.
> Updates dev and prod scripts to match 'sorbet-api' repo

- .env.example
- package.json
- src/app/container.tsx
- src/app/layout.tsx
- src/components/Header/notifications.css
- src/components/Header/notifications.tsx
- src/components/index.ts
- src/components/notifications/index.ts
- src/components/notifications/notification-toasts.tsx
- yarn.lock
> feat(notifications): add in-app notifications

- src/app/container.tsx
- src/app/gigs/gigs-board.tsx
- src/app/gigs/gigs-container.tsx
- src/components/Header/header.tsx
- src/components/Header/notifications.tsx
- src/components/ui/tabs.tsx
- src/hooks/gigs/useFetchOffers.ts
- src/types/gigs.ts
- src/types/user.ts
> feat(auth): using single account type for gigs and contracts

- .env.example
- package.json
- src/api/gigs.ts
- src/app/gigs/contract/contract-client-milestone.tsx
- src/app/gigs/contract/contract-container.tsx
- src/app/gigs/contract/contract-overview.tsx
- src/app/gigs/gigs-board.tsx
- src/app/gigs/gigs-card.tsx
- src/app/gigs/gigs-comms.tsx
- src/app/gigs/gigs-container.tsx
- src/components/sidebar/sidebar.tsx
- src/constant/constant.ts
- src/hooks/gigs/useFetchOffers.ts
- src/lib/helper.ts
- src/types/gigs.ts
- yarn.lock
> feat(smart-contract): integrate gigs with onchain data

- src/app/[username]/page.tsx
- src/app/gigs/contract/contract-client-milestone.tsx
- src/components/Header/header.tsx
- src/components/common/loading/Loading.tsx
- src/components/signin/signin-form.tsx
- src/components/signup/signup-form.tsx
- src/hooks/gigs/useGetContractForOffer.ts
- Persist user data in sign up form 
- Show when wallet is connected in login page
- Display "Sign login message" button in sign-in page when wallet is connected
- Disable **Hire Me** button when viewing your own profile
- Remove redundant console logs
- Update milestone funds verification to check NEAR balance
> refactor: across the board improvements

- src/components/signup/all-set.tsx
Updates the copy for the final "all set" step of signup. These changes were approved by Chris in design.
> Update all set copy

- .vscode/settings.json
- README.md
- package.json
This PR updates the README with relevant quick start information for new devs. These are the verbal steps I successfully followed to get up and running.
Additionally, I add a `packageManager` field to `package.json` which instructs [Corepack](https://yarnpkg.com/corepack) to lock everyone into the same version of yarn. This avoids "works on my machine" issues.
I also add a line to the `.vscode/settings` to default code to format with prettier. This is useful in a case like my own where I have a different default formatter, but want format on save to work out of the box with this repo.
> Onboarding Updates

- src/components/profile/widgets/resize-widget.tsx
- src/components/profile/widgets/util.tsx
- src/components/profile/widgets/widget-behance.tsx
- src/components/profile/widgets/widget-container.tsx
- src/components/profile/widgets/widget-dribbble.tsx
- src/components/profile/widgets/widget-figma.tsx
- src/components/profile/widgets/widget-github.tsx
- src/components/profile/widgets/widget-instagram.tsx
- src/components/profile/widgets/widget-link.tsx
- src/components/profile/widgets/widget-linkedin-profile.tsx
- src/components/profile/widgets/widget-medium.tsx
- src/components/profile/widgets/widget-photo.tsx
- src/components/profile/widgets/widget-soundcloud.tsx
- src/components/profile/widgets/widget-spotify-album.tsx
- src/components/profile/widgets/widget-spotify-song.tsx
- src/components/profile/widgets/widget-substack.tsx
- src/components/profile/widgets/widget-twitter.tsx
- src/components/profile/widgets/widget-youtube.tsx
- src/components/profile/widgets/widget.tsx
- src/lib/service/widgets.ts
- src/types/profile.ts
- src/types/widgets.ts
- Convert WidgetType to string union
- Convert WidgetSize to string union
> Widgets use string unions

- src/components/profile/profile-header.tsx
- Hot fix for wrong arg for clipboard
> Refactor: adds proper argument to clipboard

- src/components/profile/profile-header.tsx
- src/components/profile/profile.tsx
- Adds location to profile header of a user's profile
- Refactors to match figma design
> Adds location user profile

- README.md
- package.json
- Update readme with more professional info
- Update dev instructions to be accurate
- Add info about new env worflow
- Add gcloud env scripts to push and pull local env to gcloud
> Update readme and add gcloud env scripts

- src/components/onboarding/signup/step1.tsx
- Disables next button in `Step1.tsx` by checking the length of the `error` obj provided by React Hook Form.
- Every other step, the data is optional so there won't be any form errors
> SRBT-177 Disables next button if form errors are present in signup flow.

- src/components/profile/share/components/share-link.tsx
- Changes `sorbet.xyz` to `sorbet.io` in `share-link.tsx`
> SRBT-214 Changes sorbet.xyz to sorbet.io in share profile

- src/components/onboarding/signup/step1.tsx
- src/hooks/useAuth.tsx
- Update handle placeholder
- Limit handles to 25 chars 
- Update "handle taken" message
- Animate in form message
- Add zod validation for handle to only contain lowercase letters, numbers, dashes, and underscores
- Add a change handler mask to transform user input as it is entered
- Properly log user object in `useAuth` (unrelated)
https://github.com/user-attachments/assets/12f19fd4-6a3a-4589-9b6a-469de91a742b
> [SRBT-217] Implement Signup Handle Mask

- src/app/wallet/wallet-container.tsx
- src/components/sidebar/sidebar.tsx
- src/hooks/index.ts
- src/hooks/useEmbeddedWalletAddress.ts
- src/hooks/useWalletBalances.ts
- Add useEmbeddedWalletAddress for use in wallet-container and sidebar
- Format eth for 4 decimals places in useWalletBalances
- Make local Balance component with proper display logic in sidebar
- Fix styling of balances
> [SRBT-222] Fix Sidebar Balances

- src/app/wallet/credit-card.tsx
- src/components/profile/widgets/widget-photo.tsx
> Disable credit card and round image widget

- src/app/layout.tsx
> Fixes metadataBase url

- src/components/profile/widgets/play-button.tsx
- src/components/profile/widgets/widget-soundcloud.tsx
- src/components/profile/widgets/widget-spotify-album.tsx
- src/components/profile/widgets/widget-spotify-song.tsx
Add PlayButton component which matches design and use it in spotify/soundcloud widgets
> Play Button Update

- src/components/sidebar/sidebar.tsx
- Comments the `WalletAddress` component in `sidebar.tsx` for demo purposes
> Hides copy address functionality for demo purposes

- src/components/onboarding/signup/all-set.stories.tsx
- src/components/onboarding/signup/all-set.tsx
- src/components/onboarding/signup/step3.tsx
Update all set component with confetti
Move step 3 buttons to the bottom of the component
> [SRBT-206] New All Set Experience

- src/components/profile/share/components/instagram-icon.tsx
- src/components/profile/share/components/twitter-icon.tsx
> 🔥 Hotfix: Share Profile Icons

- src/api/auth.ts
- src/hooks/useAuth.tsx
**Changes**
- signUpWithPrivyId sends email in the body
Related to [Email Sync](https://github.com/MySorbet/sorbet-api/pull/46)
> [SRBT-190] Store emails in sorbet db

- src/components/onboarding/auth-hero.stories.tsx
- src/components/onboarding/auth-hero.tsx
- src/components/onboarding/onboarding-shell.stories.tsx
- src/components/onboarding/signup/all-set.stories.tsx
- src/components/onboarding/signup/all-set.tsx
- src/components/onboarding/signup/step2.stories.tsx
- src/components/onboarding/signup/user-signup.decorator.tsx
- src/components/profile/share/share-profile-dialog.stories.tsx
- src/components/profile/widgets/add-widgets.stories.tsx
- src/components/profile/widgets/onboarding-drawer/handle-input.stories.tsx
- src/components/profile/widgets/onboarding-drawer/onboarding-drawer.stories.tsx
- src/components/profile/widgets/widget-icon.stories.tsx
- src/components/profile/widgets/widget-placeholder-grid.stories.tsx
- src/components/profile/widgets/widget-placeholder.stories.tsx
- src/components/profile/widgets/widget.stories.tsx
**Changes**
- Add stories for onboarding shell
- Add stories for auth hero
- Update text in auth hero
- Wrap li in ul to fix accessibility
- Group stories by feature
- Add and use  `user-signup.decorator.tsx`
- [Edit Your Profile -> Continue to your Profile](https://linear.app/mysorbet/issue/SRBT-267/edit-your-profile-continue-to-your-profile)
> Update Onboarding Text + Storybook Updates

- src/components/profile/widgets/add-widgets.tsx
- src/components/profile/widgets/widget-grid.tsx
**Changes**
- Supporting svgs for user widgets
Screenshots/videos of the changes made (if any, otherwise delete this section)
> [SRBT-202] fix(add-widgets): adding svgs

- src/app/wallet/wallet-balance.tsx
Fixes label for send in `wallet-balances.tsx`
> Fixes label for send

- src/app/gigs/page.tsx
- src/components/common/under-development.tsx
- src/components/notifications/notifications.tsx
- src/components/profile/profile-header.tsx
- src/components/profile/share/components/instagram-icon.tsx
- src/components/profile/share/components/twitter-icon.tsx
- src/components/sidebar/sidebar.tsx
- src/lib/flags.ts
**Changes**
- Creates feature flag object to indicate feature statuses
- Removes gigs from sidebar
- Disables redirect from toasts and Knock notification popover (opens when bell icon is clicked)
- Creates a temporary under dev page for gigs
> [SRBT-316] Disable gigs

- src/hooks/profile/useGenerateQRCode.ts
**Changes**
- Updated dependency array so QR code renders properly.
Screenshots/videos of the changes made (if any, otherwise delete this section)
> [SRBT-157] Fix: QR Code not loading on Share Profile Dialog

- .storybook/decorators/use-auth.mock.tsx
- src/app/wallet/usdc-to-usd-conversion.ts
- src/app/wallet/wallet-send-dialog.tsx
**Changes**
- Fixes kebab case for `use-auth` import in `use-auth.mock.tsx`
Screenshots/videos of the changes made (if any, otherwise delete this section)
> Fixes use auth import for staging build

- src/app/wallet/all/transactions-browser.tsx
- src/app/wallet/all/transactions-table.tsx
- src/app/wallet/wallet-balance.stories.tsx
**Changes**
- Updated the wallet balance storybook to match the current wallet balance
- Fixed minor hydration error where a `div` was the child of a `tbody`
- Refactored fetchTransactions() into a useCallback() hook to avoid the dependencies of useEffect Hook change on every render.
> [SRBT-323] Building on wallet page works properly

- src/lib/env.ts
**Changes**
- Update `NEXT_PUBLIC_BASESEPOLIA_EXPLORER` to `NEXT_PUBLIC_BASE_EXPLORER`
Note: after pulling this, run `yarn env`
> # [SRBT-326] Mainnet Fixes

- src/app/wallet/wallet-container.tsx
**Changes**
- The USDC balance is now updated when the user finishes the `Top Off` flow.
> [SRBT-325] adding a reload after top off

- src/components/profile/widgets/resize-widget.tsx
- src/components/profile/widgets/widget.tsx
- src/hooks/profile/useWidgetManagement.ts
**Changes**
- Before, you had to refresh the page for widget linking functionality to work with image widgets. Now feedback is instantaneous.
https://github.com/user-attachments/assets/4528b3d3-616f-4c1b-ba4d-b0b1e0149747
> [SRBT-360] Fix the ability to add and remove links immediately

- src/components/profile/widgets/widget-soundcloud.tsx
- src/components/profile/widgets/widget-twitter.tsx
- src/components/profile/widgets/widget-youtube.tsx
**Changes**
- removed className string to fix build errors
> Build Error Fix

- src/api/auth.ts
- src/app/signin/components/signin-content.stories.tsx
- src/app/signin/components/signin-content.tsx
- src/app/signin/page.tsx
- src/hooks/use-auth.tsx
- src/lib/flags.ts
**Changes**
- Add new sign in component
- Send signin/signups to dashboard rather than handle
> [SRBT-378] Implement new signin

- .storybook/preview.ts
- src/api/transactions/transactions.ts
- src/app/dashboard/components/dashboard.stories.tsx
- src/app/dashboard/components/transaction-card.tsx
- src/app/dashboard/page.tsx
- src/app/wallet/components/transaction-table.tsx
- src/app/wallet/hooks/use-transaction-overview.ts
- src/components/header/header.tsx
- tailwind.config.ts
**Changes**
- Use white SB bg
- Add designed empty state for <TransactionCard/>
- White background on dashboard
- wrap transaction card button
- Use only 1rem padding for tailwind containers
- Transaction card does not send last_days
>  More Dashboard Polish

- src/api/invoices/sample-invoices.tsx
- src/app/invoices/components/create/invoice-details.tsx
- src/app/invoices/components/create/invoice-form-context.tsx
- src/app/invoices/components/dashboard/utils.tsx
- src/app/invoices/components/invoice-document.stories.tsx
- src/app/invoices/components/invoice-document.tsx
**Changes**
- Add tax to form schema, invoice-details, and invoice-document
- Add a story for invoice document with form data
> [SRBT-388] Add Sales Tax

- package.json
- src/app/wallet/components/balance-card/balance-card.tsx
- src/app/wallet/components/wallet-summary-card.tsx
- src/app/wallet/hooks/use-send-usdc.ts
- src/app/wallet/hooks/use-top-up.ts
- src/components/notifications/notification-toasts.tsx
- yarn.lock
**User facing Changes**
- Refetch both balance and transaction overview on send
- Update top up error messaging
- Refetch balance and transactions when payment notification is received
**Dev Changes**
- Removed old code from notification-toasts
- type notification event handlers
> More Misc Bug Fixes

- src/api/user/mock-user.ts
- src/app/v2/[handle]/components/onboard-with-handles.stories.tsx
- src/app/v2/[handle]/components/onboard-with-handles.tsx
- src/app/v2/[handle]/components/profile-details.stories.tsx
- src/app/v2/[handle]/components/profile-details.tsx
- src/app/v2/[handle]/components/profile.stories.tsx
- src/app/v2/[handle]/components/profile.tsx
- src/lib/utils.ts
- src/types/user.ts
**Changes**
- Add edit-profile-sheet to profile 2.0
- Add support for placeholders when there is no name or bio 
- Move towards a correct user type
- Add a name format utility to utils
- Add first version of OnboardWithHandles component
> Profile 2.0 Upgrades

- src/app/v2/[handle]/components/profile-details.tsx
- src/app/v2/[handle]/components/tip.tsx
- src/app/v2/[handle]/hooks/use-connect-and-send.tsx
> Implement profile tipping

- src/api/recipients/recipients.ts
- src/app/(with-sidebar)/recipients/components/recipient-page-content.tsx
- src/app/(with-sidebar)/recipients/components/recipient-sheet.stories.tsx
- src/app/(with-sidebar)/recipients/components/recipient-sheet.tsx
- src/app/(with-sidebar)/recipients/components/recipients-card.tsx
- src/app/(with-sidebar)/recipients/hooks/use-delete-recipient.ts
**Changes**
- Enable recipient delete in table and sheet
- Disable delete for non crypto recipients
> Enable recipient delete (only crypto)

- src/api/bridge/bridge.ts
- src/api/bridge/mock-bridge-customer.ts
- src/api/bridge/msw-handlers.ts
- src/app/(with-sidebar)/accounts/components/accounts-page-content.stories.tsx
- src/app/(with-sidebar)/accounts/components/accounts-page-content.tsx
- src/app/(with-sidebar)/accounts/components/verification/automatic-verification-tabs.stories.tsx
- src/app/(with-sidebar)/accounts/components/verification/automatic-verification-tabs.tsx
- src/app/(with-sidebar)/accounts/components/verification/verification-tabs.stories.tsx
- src/app/(with-sidebar)/accounts/components/verification/verification-tabs.tsx
- src/app/(with-sidebar)/accounts/hooks/use-claim-virtual-account.tsx
- src/app/(with-sidebar)/verify/components/account-verification-card.tsx
- src/components/app-sidebar/app-sidebar.tsx
- src/hooks/use-flags.ts
- src/types/bridge.ts
**Changes**
- Add claim flags to types
- Update verify page to use claim endpoint to create bridge customer
- More robust end states
- Fix bug where mock data was being used
- Add indeterminacy
- Render mobile verification in drawer (needs work)
> Implement VA claiming

- src/api/transactions/transactions.ts
- src/app/(with-sidebar)/recipients/components/send/send-to-form.tsx
- src/app/(with-sidebar)/recipients/components/send/success.tsx
- src/app/(with-sidebar)/wallet/components/transaction-table.tsx
- src/app/(with-sidebar)/wallet/components/transactions-browser.tsx
- src/app/(with-sidebar)/wallet/components/utils.tsx
- src/app/(with-sidebar)/wallet/hooks/use-transaction-overview.ts
- src/components/common/transaction-status-badge.tsx
- src/types/bridge.ts
- src/types/transactions.ts
**Changes**
- Display statuses in the transaction table
- Update transaction fetching to be based on privy ID rather than address 
- Move TransactionStatusBadge to common
> Implement Transaction Status

- src/app/(with-sidebar)/dashboard/components/checklist-card.tsx
- src/app/(with-sidebar)/verify/components/account-verification-card.tsx
- src/app/(with-sidebar)/verify/components/faq.tsx
- src/app/(with-sidebar)/verify/components/kyc-checklist.tsx
- src/app/(with-sidebar)/verify/components/persona-card.tsx
- src/app/(with-sidebar)/verify/components/verify-dashboard.tsx
- src/app/signin/components/business/card-button.tsx
- src/app/signin/components/business/individual-or-business.stories.tsx
- src/app/signin/components/business/individual-or-business.tsx
- src/app/signin/components/signin-content.tsx
- src/components/app-sidebar/app-sidebar.tsx
- src/hooks/use-auth.tsx
- src/types/user.ts
**Changes**
- Use generic language around verification
- Fix bug where claiming an account was in incorrect state before customer created event is received
- Add customer type selection to signin
- Display rejection reasons in under review state
> Implement KYB
